/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-02 02:36:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/menu_main.jsp", Long.valueOf(1585790580415L));
    _jspx_dependants.put("/WEB-INF/views/menu_admin.jsp", Long.valueOf(1585632802673L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582768957599L));
    _jspx_dependants.put("jar:file:/C:/study/springstudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Web_Project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/bottom.jsp", Long.valueOf(1585202317451L));
    _jspx_dependants.put("/WEB-INF/views/admin_item_add.jsp", Long.valueOf(1585794958551L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사용자 메뉴</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("\tmargin : 0;\r\n");
      out.write("\tpadding : 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>menu main</title>\r\n");
      out.write("<link rel = \"stylesheet\" href=\"resources/css/cust_tb.css\">\r\n");
      out.write("<link rel = \"stylesheet\"  href=\"resources/css/sw_layout.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t#main_menu_bar {\r\n");
      out.write("  \t\tlist-style-type: none;\r\n");
      out.write("  \t\tmargin: 0;\r\n");
      out.write("  \t\toverflow: hidden;\r\n");
      out.write("  \t\tbackground-color : lightcoral;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#main_menu_bar li {\r\n");
      out.write("  \t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\tli a, .dropbtn {\r\n");
      out.write(" \t\tdisplay: inline-block;\r\n");
      out.write("  \t\tcolor: white;\r\n");
      out.write("  \t\ttext-align: center;\r\n");
      out.write("  \t\tpadding: 14px 16px; \r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#main_menu_bar li a:hover, .dropdown:hover .dropbtn {\r\n");
      out.write("  \t\tbackground-color: #ff1a48;\r\n");
      out.write("  \t\tColor : black;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tli.dropdown { display: inline-block;}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content {\r\n");
      out.write("  \t\tdisplay: none;\r\n");
      out.write("  \t\tposition: absolute;\r\n");
      out.write("  \t\tbackground-color : lightcoral;\r\n");
      out.write("  \t\tcolor : white;\r\n");
      out.write("  \t\tmin-width: 160px;\r\n");
      out.write("  \t\tbox-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("  \t\tz-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content a {\r\n");
      out.write(" \t \tcolor: white;\r\n");
      out.write("  \t\tpadding: 12px 16px; \r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("  \t\ttext-align: left;\r\n");
      out.write("\t\tfloat : left\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content a:hover \r\n");
      out.write("\t{\r\n");
      out.write("\t\tbackground-color: #ff4c4c;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown:hover .dropdown-content {\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t#icon_img {\r\n");
      out.write("\t\tpostion : right;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<img src=\"resources/images/banner2.png\" alt=\"top_banner\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul id = \"main_menu_bar\">\r\n");
      out.write("\t\t<li><a href=\"home.do\">Home</a></li>\r\n");
      out.write("  \t\t<li class = \"dropdown\"><a href=\"item.do?item_category=1\" class=\"dropbtn\">Menu</a>\r\n");
      out.write("  \t\t\t<div class=\"dropdown-content\" >\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=1\">Cookie & Muffin </a>\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=2\">Bread</a>\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=3\">Dessert</a>\r\n");
      out.write("      \t\t\t<!-- <a href = \"address_test.do\">주소테스트</a> -->\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</li>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<!-- <li><a href=\"index.do?cntPage=event\">Event</a></li> -->\r\n");
      out.write("  \t\t<li><a href=\"event.do\">Event</a></li>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<li class = \"dropdown\"><a href=\"main_notice.do\" class=\"dropbtn\">고객센터</a>\t\t\t\r\n");
      out.write("  \t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("      \t\t\t<a href=\"main_notice.do\">공지사항</a>\r\n");
      out.write("      \t\t\t<a href=\"item_qa.do\">Q/A</a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div id = icon_img>\r\n");
      out.write("  \t\t<a href=\"index_cust.do?cntPage=custCart\"><img src=\"resources/images/cart.png\" alt=\"cart\" style=\"float:right;width:42px;height:42px;\"></a>\r\n");
      out.write(" \t\t<a href=\"login.do\"><img src=\"resources/images/login.png\" alt=\"login\" style=\"float:right;width:42px;height:42px;\"></a>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </p>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div class = \"admin_content\"> ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/sw_layout.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\t/* *{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tline-height: 1.6;\r\n");
      out.write("\t\tmargin : 0;\r\n");
      out.write("\t\tpadding : 0;\r\n");
      out.write("\t} */\r\n");
      out.write("\t/* Style the side navigation */\r\n");
      out.write("\t.admin_content {\r\n");
      out.write("  \t\theight: 100%;\r\n");
      out.write("  \t\twidth: 200px;\r\n");
      out.write("  \t\tposition: absolute;\r\n");
      out.write("  \t\tbackground-color: lightcoral;\r\n");
      out.write("  \t\t/* margin: 5px; */\r\n");
      out.write("  \t\tpadding: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* Side navigation links */\r\n");
      out.write("\t.admin_content  a {\r\n");
      out.write("  \t\tcolor: white;\r\n");
      out.write(" \t\tpadding: 16px;\r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Change color on hover */\r\n");
      out.write("\t.admin_content  a:hover {\r\n");
      out.write(" \t\tbackground-color: #ff1a48;\r\n");
      out.write("  \t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"sidenav\">\r\n");
      out.write("\t\t<a href=\"admin_order.do\" >주문배송처리</a>\r\n");
      out.write("  \t\t<a href=\"admin_review.do\">구매후기</a>\r\n");
      out.write("  \t\t<a href=\"item_qa.do\">Q/A</a>\r\n");
      out.write("  \t\t<a href=\"admin_item_add.do\">메뉴 추가/수정</a>\r\n");
      out.write("  \t\t<a href=\"admin_event_add.do\">이벤트 추가/수정</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" </div>\r\n");
      out.write("      <div class = \"main_content\">  ");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Edit Event</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/sw_form.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/sw_layout.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('ul.tabs li').click(function() {\r\n");
      out.write("\t\t\tvar tab_id = $(this).attr('data-tab');\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('ul.tabs li').removeClass('current');\r\n");
      out.write("\t\t\t$('.tab-content').removeClass('current');\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(this).addClass('current');\r\n");
      out.write("\t\t\t$(\"#\" + tab_id).addClass('current');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction insert_item(f) {\r\n");
      out.write("\t\t\tf.action= \"insert_item.do\";\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".container {\r\n");
      out.write("\t/* width: 500px;\r\n");
      out.write("\t\tmargin: 0 auto; */\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tmargin: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs {\r\n");
      out.write("\t/* margin: 0px; */\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs li {\r\n");
      out.write("\tbackground: lightcoral;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 10px 15px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.tabs li.current {\r\n");
      out.write("\tborder: 1px soild lightcoral;\r\n");
      out.write("\tbackground: #ff4c4c;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\t/* background: lightcoral; */\r\n");
      out.write("\tpadding: 10px 15px; /* 15px; */\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("\tborder: 1px soild lightcoral;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab-content.current {\r\n");
      out.write("\tdisplay: inherit;\r\n");
      out.write("\tborder: 1px solid lightcoral;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>menu main</title>\r\n");
      out.write("<link rel = \"stylesheet\" href=\"resources/css/cust_tb.css\">\r\n");
      out.write("<link rel = \"stylesheet\"  href=\"resources/css/sw_layout.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t#main_menu_bar {\r\n");
      out.write("  \t\tlist-style-type: none;\r\n");
      out.write("  \t\tmargin: 0;\r\n");
      out.write("  \t\toverflow: hidden;\r\n");
      out.write("  \t\tbackground-color : lightcoral;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#main_menu_bar li {\r\n");
      out.write("  \t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\tli a, .dropbtn {\r\n");
      out.write(" \t\tdisplay: inline-block;\r\n");
      out.write("  \t\tcolor: white;\r\n");
      out.write("  \t\ttext-align: center;\r\n");
      out.write("  \t\tpadding: 14px 16px; \r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#main_menu_bar li a:hover, .dropdown:hover .dropbtn {\r\n");
      out.write("  \t\tbackground-color: #ff1a48;\r\n");
      out.write("  \t\tColor : black;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tli.dropdown { display: inline-block;}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content {\r\n");
      out.write("  \t\tdisplay: none;\r\n");
      out.write("  \t\tposition: absolute;\r\n");
      out.write("  \t\tbackground-color : lightcoral;\r\n");
      out.write("  \t\tcolor : white;\r\n");
      out.write("  \t\tmin-width: 160px;\r\n");
      out.write("  \t\tbox-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("  \t\tz-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content a {\r\n");
      out.write(" \t \tcolor: white;\r\n");
      out.write("  \t\tpadding: 12px 16px; \r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("  \t\ttext-align: left;\r\n");
      out.write("\t\tfloat : left\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown-content a:hover \r\n");
      out.write("\t{\r\n");
      out.write("\t\tbackground-color: #ff4c4c;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.dropdown:hover .dropdown-content {\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t#icon_img {\r\n");
      out.write("\t\tpostion : right;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<img src=\"resources/images/banner2.png\" alt=\"top_banner\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<ul id = \"main_menu_bar\">\r\n");
      out.write("\t\t<li><a href=\"home.do\">Home</a></li>\r\n");
      out.write("  \t\t<li class = \"dropdown\"><a href=\"item.do?item_category=1\" class=\"dropbtn\">Menu</a>\r\n");
      out.write("  \t\t\t<div class=\"dropdown-content\" >\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=1\">Cookie & Muffin </a>\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=2\">Bread</a>\r\n");
      out.write("      \t\t\t<a href=\"item.do?item_category=3\">Dessert</a>\r\n");
      out.write("      \t\t\t<!-- <a href = \"address_test.do\">주소테스트</a> -->\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</li>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<!-- <li><a href=\"index.do?cntPage=event\">Event</a></li> -->\r\n");
      out.write("  \t\t<li><a href=\"event.do\">Event</a></li>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<li class = \"dropdown\"><a href=\"main_notice.do\" class=\"dropbtn\">고객센터</a>\t\t\t\r\n");
      out.write("  \t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("      \t\t\t<a href=\"main_notice.do\">공지사항</a>\r\n");
      out.write("      \t\t\t<a href=\"item_qa.do\">Q/A</a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div id = icon_img>\r\n");
      out.write("  \t\t<a href=\"index_cust.do?cntPage=custCart\"><img src=\"resources/images/cart.png\" alt=\"cart\" style=\"float:right;width:42px;height:42px;\"></a>\r\n");
      out.write(" \t\t<a href=\"login.do\"><img src=\"resources/images/login.png\" alt=\"login\" style=\"float:right;width:42px;height:42px;\"></a>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </p>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div class = \"admin_content\">");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/sw_layout.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\t/* *{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tline-height: 1.6;\r\n");
      out.write("\t\tmargin : 0;\r\n");
      out.write("\t\tpadding : 0;\r\n");
      out.write("\t} */\r\n");
      out.write("\t/* Style the side navigation */\r\n");
      out.write("\t.admin_content {\r\n");
      out.write("  \t\theight: 100%;\r\n");
      out.write("  \t\twidth: 200px;\r\n");
      out.write("  \t\tposition: absolute;\r\n");
      out.write("  \t\tbackground-color: lightcoral;\r\n");
      out.write("  \t\t/* margin: 5px; */\r\n");
      out.write("  \t\tpadding: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* Side navigation links */\r\n");
      out.write("\t.admin_content  a {\r\n");
      out.write("  \t\tcolor: white;\r\n");
      out.write(" \t\tpadding: 16px;\r\n");
      out.write("  \t\ttext-decoration: none;\r\n");
      out.write("  \t\tdisplay: block;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Change color on hover */\r\n");
      out.write("\t.admin_content  a:hover {\r\n");
      out.write(" \t\tbackground-color: #ff1a48;\r\n");
      out.write("  \t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"sidenav\">\r\n");
      out.write("\t\t<a href=\"admin_order.do\" >주문배송처리</a>\r\n");
      out.write("  \t\t<a href=\"admin_review.do\">구매후기</a>\r\n");
      out.write("  \t\t<a href=\"item_qa.do\">Q/A</a>\r\n");
      out.write("  \t\t<a href=\"admin_item_add.do\">메뉴 추가/수정</a>\r\n");
      out.write("  \t\t<a href=\"admin_event_add.do\">이벤트 추가/수정</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" </div>\r\n");
      out.write("\t<div class = \"main_content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<ul class=\"tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"tab-link current\" data-tab=\"tab-1\">아이템 수정</li>\r\n");
      out.write("\t\t\t\t<li class=\"tab-link\" data-tab=\"tab-2\">아이템 추가</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"tab-1\" class=\"tab-content current\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<thead></thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품번호:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"item_no\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"button\">검색</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품분류:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><select id=\"sel_item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Snack</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">Bread</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">Dessert</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품이름 :</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>이미지 파일 위치:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"img_path\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button type=\"button\">IMG Upload</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품소개:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"img_path\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품 구성 재료:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"img_path\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품 가격:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_price\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">알레르기 분류:</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">유제품</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">땅콩</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">밀가루</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">글루텐프리 O</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">글루텐프리X</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">베지테리안 O</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">락토 오버</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">베지테리안 X</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">배송시 유의사항:</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><textarea>배송시 유의사항....</textarea>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"3\" align=\"center\"><button type=\"button\">수정</button><button type=\"button\">취소</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tfoot></tfoot>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tab-2\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<form method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<thead></thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품분류:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><select id=\"item_category\" name = \"item_category\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">Snack</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">Bread</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">Dessert</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품이름 :</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품소개:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_spec\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>제품가격:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"number\" name=\"item_price\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>총내용량:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_cal\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>구성성분:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_content\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>알레르기:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"text\" name=\"item_aller\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>이미지 파일 위치:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan = \"2\"><input type=\"file\" name=\"file\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"3\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" value=\"입력\" onclick=\"insert_item(this.form)\">입력</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"reset\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tfoot></tfoot>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p>Copyright 2020 SweetForest</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" </div>  \r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p>Copyright 2020 SweetForest</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
